import { SkinSpriteName } from '@sonolus/core'

export const skin = defineSkin({
    sprites: {
        cover: SkinSpriteName.StageCover,
        lane: SkinSpriteName.Lane,
        judgmentLine: SkinSpriteName.JudgmentLine,
        stageLeftBorder: SkinSpriteName.StageLeftBorder,
        stageRightBorder: SkinSpriteName.StageRightBorder,
        sekaiStage: 'Sekai Stage',
        sekaiStageCover: 'Sekai Stage Cover',
        sekaiStageLane: 'Sekai Stage Lane',
        simLine: SkinSpriteName.SimultaneousConnectionNeutral,
        normalNoteLeft: 'Sekai Note Cyan Left',
        normalNoteMiddle: 'Sekai Note Cyan Middle',
        normalNoteRight: 'Sekai Note Cyan Right',
        normalNoteFallback: SkinSpriteName.NoteHeadCyan,
        slideNoteLeft: 'Sekai Note Green Left',
        slideNoteMiddle: 'Sekai Note Green Middle',
        slideNoteRight: 'Sekai Note Green Right',
        slideNoteFallback: SkinSpriteName.NoteHeadGreen,
        slideNoteEndFallback: SkinSpriteName.NoteTailGreen,
        flickNoteLeft: 'Sekai Note Red Left',
        flickNoteMiddle: 'Sekai Note Red Middle',
        flickNoteRight: 'Sekai Note Red Right',
        flickNoteFallback: SkinSpriteName.NoteHeadRed,
        flickNoteEndFallback: SkinSpriteName.NoteTailRed,
        criticalNoteLeft: 'Sekai Note Yellow Left',
        criticalNoteMiddle: 'Sekai Note Yellow Middle',
        criticalNoteRight: 'Sekai Note Yellow Right',
        criticalNoteFallback: SkinSpriteName.NoteHeadYellow,
        criticalNoteEndFallback: SkinSpriteName.NoteTailYellow,
        normalSlideTickNote: 'Sekai Diamond Green',
        normalSlideTickNoteFallback: SkinSpriteName.NoteTickGreen,
        criticalSlideTickNote: 'Sekai Diamond Yellow',
        criticalSlideTickNoteFallback: SkinSpriteName.NoteTickYellow,
        traceFlickNote: 'Sekai Trace Note Red',
        traceFlickNoteLeft: 'Sekai Trace Note Red Left',
        traceFlickNoteMiddle: 'Sekai Trace Note Red Middle',
        traceFlickNoteRight: 'Sekai Trace Note Red Right',
        traceFlickNoteDiamond: 'Sekai Trace Diamond Red',
        traceFlickNoteFallback: SkinSpriteName.NoteTickRed,
        normalTraceNote: 'Sekai Trace Note Green',
        normalTraceNoteLeft: 'Sekai Trace Note Green Left',
        normalTraceNoteMiddle: 'Sekai Trace Note Green Middle',
        normalTraceNoteRight: 'Sekai Trace Note Green Right',
        normalTraceNoteDiamond: 'Sekai Trace Diamond Green',
        normalTraceNoteFallback: SkinSpriteName.NoteTickGreen,
        criticalTraceNote: 'Sekai Trace Note Yellow',
        criticalTraceNoteLeft: 'Sekai Trace Note Yellow Left',
        criticalTraceNoteMiddle: 'Sekai Trace Note Yellow Middle',
        criticalTraceNoteRight: 'Sekai Trace Note Yellow Right',
        criticalTraceNoteDiamond: 'Sekai Trace Diamond Yellow',
        criticalTraceNoteFallback: SkinSpriteName.NoteTickYellow,
        damageNoteLeft: 'Sekai Trace Note Purple Left',
        damageNoteMiddle: 'Sekai Trace Note Purple Middle',
        damageNoteRight: 'Sekai Trace Note Purple Right',
        damageNoteFallback: SkinSpriteName.NoteTickPurple,
        guideGreen: 'Sekai Guide Green',
        guideYellow: 'Sekai Guide Yellow',
        guideBlue: 'Sekai Guide Blue',
        guideNeutral: 'Sekai Guide Neutral',
        guideRed: 'Sekai Guide Red',
        guideCyan: 'Sekai Guide Cyan',
        guidePurple: 'Sekai Guide Purple',
        guideBlack: 'Sekai Guide Black',
        normalActiveSlideConnectorNormal: 'Sekai Active Slide Connection Green',
        normalActiveSlideConnectorActive: 'Sekai Active Slide Connection Green Active',
        normalActiveSlideConnectorFallback: SkinSpriteName.NoteConnectionGreenSeamless,
        criticalActiveSlideConnectorNormal: 'Sekai Active Slide Connection Yellow',
        criticalActiveSlideConnectorActive: 'Sekai Active Slide Connection Yellow Active',
        criticalActiveSlideConnectorFallback: SkinSpriteName.NoteConnectionYellowSeamless,
        normalSlotGlow: 'Sekai Slot Glow Cyan',
        slideSlotGlow: 'Sekai Slot Glow Green',
        normalSlideConnectorSlotGlow: 'Sekai Slot Glow Green Slider Hold',
        flickSlotGlow: 'Sekai Slot Glow Red',
        criticalSlotGlow: 'Sekai Slot Glow Yellow',
        criticalFlickSlotGlow: 'Sekai Slot Glow Yellow Flick',
        criticalSlideConnectorSlotGlow: 'Sekai Slot Glow Yellow Slider Hold',
        criticalSlideNoteSlotGlow: 'Sekai Slot Glow Yellow Slider Tap',
        normalSlot: 'Sekai Slot Cyan',
        slideSlot: 'Sekai Slot Green',
        flickSlot: 'Sekai Slot Red',
        criticalSlot: 'Sekai Slot Yellow',
        criticalFlickSlot: 'Sekai Slot Yellow Flick',
        criticalSlideSlot: 'Sekai Slot Yellow Slider',
        flickArrowUp1: 'Sekai Flick Arrow Red Up 1',
        flickArrowUp2: 'Sekai Flick Arrow Red Up 2',
        flickArrowUp3: 'Sekai Flick Arrow Red Up 3',
        flickArrowUp4: 'Sekai Flick Arrow Red Up 4',
        flickArrowUp5: 'Sekai Flick Arrow Red Up 5',
        flickArrowUp6: 'Sekai Flick Arrow Red Up 6',
        flickArrowLeft1: 'Sekai Flick Arrow Red Up Left 1',
        flickArrowLeft2: 'Sekai Flick Arrow Red Up Left 2',
        flickArrowLeft3: 'Sekai Flick Arrow Red Up Left 3',
        flickArrowLeft4: 'Sekai Flick Arrow Red Up Left 4',
        flickArrowLeft5: 'Sekai Flick Arrow Red Up Left 5',
        flickArrowLeft6: 'Sekai Flick Arrow Red Up Left 6',
        flickArrowDown1: 'Sekai Flick Arrow Red Down 1',
        flickArrowDown2: 'Sekai Flick Arrow Red Down 2',
        flickArrowDown3: 'Sekai Flick Arrow Red Down 3',
        flickArrowDown4: 'Sekai Flick Arrow Red Down 4',
        flickArrowDown5: 'Sekai Flick Arrow Red Down 5',
        flickArrowDown6: 'Sekai Flick Arrow Red Down 6',
        flickArrowDownLeft1: 'Sekai Flick Arrow Red Down Left 1',
        flickArrowDownLeft2: 'Sekai Flick Arrow Red Down Left 2',
        flickArrowDownLeft3: 'Sekai Flick Arrow Red Down Left 3',
        flickArrowDownLeft4: 'Sekai Flick Arrow Red Down Left 4',
        flickArrowDownLeft5: 'Sekai Flick Arrow Red Down Left 5',
        flickArrowDownLeft6: 'Sekai Flick Arrow Red Down Left 6',
        flickArrowFallback: SkinSpriteName.DirectionalMarkerRed,
        criticalArrowUp1: 'Sekai Flick Arrow Yellow Up 1',
        criticalArrowUp2: 'Sekai Flick Arrow Yellow Up 2',
        criticalArrowUp3: 'Sekai Flick Arrow Yellow Up 3',
        criticalArrowUp4: 'Sekai Flick Arrow Yellow Up 4',
        criticalArrowUp5: 'Sekai Flick Arrow Yellow Up 5',
        criticalArrowUp6: 'Sekai Flick Arrow Yellow Up 6',
        criticalArrowLeft1: 'Sekai Flick Arrow Yellow Up Left 1',
        criticalArrowLeft2: 'Sekai Flick Arrow Yellow Up Left 2',
        criticalArrowLeft3: 'Sekai Flick Arrow Yellow Up Left 3',
        criticalArrowLeft4: 'Sekai Flick Arrow Yellow Up Left 4',
        criticalArrowLeft5: 'Sekai Flick Arrow Yellow Up Left 5',
        criticalArrowLeft6: 'Sekai Flick Arrow Yellow Up Left 6',
        criticalArrowDown1: 'Sekai Flick Arrow Yellow Down 1',
        criticalArrowDown2: 'Sekai Flick Arrow Yellow Down 2',
        criticalArrowDown3: 'Sekai Flick Arrow Yellow Down 3',
        criticalArrowDown4: 'Sekai Flick Arrow Yellow Down 4',
        criticalArrowDown5: 'Sekai Flick Arrow Yellow Down 5',
        criticalArrowDown6: 'Sekai Flick Arrow Yellow Down 6',
        criticalArrowDownLeft1: 'Sekai Flick Arrow Yellow Down Left 1',
        criticalArrowDownLeft2: 'Sekai Flick Arrow Yellow Down Left 2',
        criticalArrowDownLeft3: 'Sekai Flick Arrow Yellow Down Left 3',
        criticalArrowDownLeft4: 'Sekai Flick Arrow Yellow Down Left 4',
        criticalArrowDownLeft5: 'Sekai Flick Arrow Yellow Down Left 5',
        criticalArrowDownLeft6: 'Sekai Flick Arrow Yellow Down Left 6',
        criticalArrowFallback: SkinSpriteName.DirectionalMarkerYellow,
        perfect: 'Perfect',
        great: 'Great',
        good: 'Good',
        bad: 'Bad',
        miss: 'Miss',
        ap0: 'AP0',
        ap1: 'AP1',
        ap2: 'AP2',
        ap3: 'AP3',
        ap4: 'AP4',
        ap5: 'AP5',
        ap6: 'AP6',
        ap7: 'AP7',
        ap8: 'AP8',
        ap9: 'AP9',
        c0: 'C0',
        c1: 'C1',
        c2: 'C2',
        c3: 'C3',
        c4: 'C4',
        c5: 'C5',
        c6: 'C6',
        c7: 'C7',
        c8: 'C8',
        c9: 'C9',
        combo: 'Combo',
        apCombo: 'APCombo',
        fast: 'Fast',
        late: 'Late',
        flick: 'Flick',
        auto: 'Auto',
        glow0: 'Glow0',
        glow1: 'Glow1',
        glow2: 'Glow2',
        glow3: 'Glow3',
        glow4: 'Glow4',
        glow5: 'Glow5',
        glow6: 'Glow6',
        glow7: 'Glow7',
        glow8: 'Glow8',
        glow9: 'Glow9',
        glowCombo: 'GlowCombo',
        damage: 'Damage',
    },
})
export const layer = {
    cover: 1000,
    judgment: 1000,
    damage: 500,
    slotGlowEffect: 25,
    note: {
        arrow: 24,
        tick: 23,
        body: 22,
        trace: 20,
        connector: 11,
        guide: 12,
    },
    simLine: 14,
    slotEffect: 3,
    judgmentLine: 2,
    stage: 0,
}
export const getZ = (layer, time, lane, etc) =>
    (1 / 128) * etc + (1 / 128) * Math.abs(lane) - time + 512 * layer
